# Generated by Django 6.0.5 on 2026-05-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fondateur', models.CharField(max_length=100)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('pays_origine', models.CharField(max_length=50)),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('energie', models.CharField(max_length=100)),
                ('nombre_chevaux', models.IntegerField()),
                ('type_moteur', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
                ('marque', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vroumvroum.marque')),
            ],
        ),
    ]
