# Generated by Django 6.0.5 on 2026-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vroumvroum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modele',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modeles/'),
        ),
    ]
